CURRENT_EPOCH: 0
TRAIN:
  DEBUG: False
  DATASET:
    NAME: TencentHand
    ROOT: data/TencentHand
    IS_TRAIN: True
    BATCH_SIZE: 2
    SHUFFLE: 0
    DATA_JSON_PATH: data/TencentHand/train.json
    TRANSFORMS: True
    NUM_JOINTS: 21
    HEATMAP:
      TYPE: Gaussian # Gaussian or Cauchy
      SIGMA: 1 #Ground truth heatmap 
VALID:
  DEBUG: False
  DATASET:
    NAME: TencentHand
    ROOT: data/TencentHand
    IS_TRAIN: False
    BATCH_SIZE: 2
    DATA_JSON_PATH: data/TencentHand/valid.json
    TRANSFORMS: True
    NUM_JOINTS: 21
    DIM_JOINT: 2
    HEATMAP:
      TYPE: Gaussian # Gaussian or Cauchy
      SIGMA: 1 #Ground truth heatmap 
DATA_DIR: ''
END_EPOCH: 100
GPUS:
- 0
- 1
- 2
- 3
LOG_DIR: ''
MODEL:
  NAME: openpose_hand
  PRETRAINED: 'pretrained_weight/iccv17_pose_net_pretrained.pickle'
  num_joints: 21
OPTIMIZER:
  NAME: RMSprop
  PARAMETERS:
    lr: 2.5e-05
    momentum: 0
    weight_decay: 0
OPTIMIZER_SCHEDULE:
  NAME: StepLR
  PARAMETERS:
    gamma: 0.1
    step_size: 30
LOG:
  PATH: output
  MONITOR_ITEM: #all the metric item would be load in monitor item automaticlly 
    - lr
OUTPUT_DIR: output/
START_EPOCH: 0
WORKERS: 8
RESUME_TRAIN: 0
