CURRENT_EPOCH: 0
IS_VALID: True #validate or just inference
DATASET:
  NAME: JointsDataset
  CONTAINS:
    STB:
      ROOT: data/STB/2dcrop
      DATA_JSON_PATH: data/STB/2dcrop/label.pickle
      PICK:
        - B1Counting
        - B1Random
  REPROCESS:
    TRANSFORMS:
      RESIZE: 256
      FLIP: False
      COLOR_NORISE: False
    HEATMAP:
      TYPE: Gaussian # Gaussian or Cauchy
      SIGMA: 8 #Ground truth heatmap
    NUM_JOINTS: 22

  IS_TRAIN: False
  BATCH_SIZE: 20

LOG_DIR: ''
MODEL:
  NAME: Weakly_direct_regression
  NETWORKS:
    Regression:
      TYPE: CPMWeaklyDirectRegression
      # PRETRAINED_WEIGHT_PATH: output/Apr_15_01:40:17_Weakly_direct_regression_with_depth_train:STB_valid:STB/best/model/net_Regression.torch
      # PRETRAINED_WEIGHT_PATH: output/Apr_14_16:55:37_Weakly_direct_regression_train:STB_valid:STB/5/model/net_Regression.torch
      PRETRAINED_WEIGHT_PATH: '/home/liangjic/cycada/cyclegan/checkpoints/STB_DEPTH/best_Regression.torch'
      # PRETRAINED_WEIGHT_PATH: 'output/c/best/model/net_Regression.torch'
      num_joints: 22

  OPTIMIZERS:
    Regression:
      NETWORKS:
        - Regression
      TYPE: RMSprop
      PARAMETERS:
        lr: 2.5e-5
        momentum: 0
        weight_decay: 0
      SCHEDULER:
        TYPE: StepLR
        PARAMETERS:
          gamma: 0.1
          step_size: 30
  GPUS: [0,1,2,3]
  STAGE: 3

METRIC_ITEMS: # the metric that you wanna track during training
  - loss
  - dis2d
  - dis3d
  - AUC_20_50
  - median
OUTPUT_DIR: infer_result/
START_EPOCH: 0
WORKERS: 1
DARW_RESULT: True
DEBUG: False
