CURRENT_EPOCH: 0
TRAIN:
  DEBUG: False
  METRIC_ITEMS: # the metric that you wanna track during training
  - loss
  - dis
  - PcKAcc
  DATASET:
    NAME: RHD2D
    ROOT: data/RHD/training/cropped_full 
    DATA_JSON_PATH: data/RHD/training/cropped_anno_full.pickle
    IS_TRAIN: True
    TRANSFORMS:
      RESIZE: 256
      FLIP: True
      COLOR_NORISE: True
    HEATMAP:
      SIGMA: 8
      TYPE: Gaussian
    IS_TRAIN: True
    BATCH_SIZE: 6
    SHUFFLE: True
    NUM_JOINTS: 21
    THR: 20

VALID:
  DEBUG: False
  IS_VALID: True
  NUM_JOINTS: 21
  METRIC_ITEMS:
    - loss
    - dis
    - PcKAcc
  DATASET:
    NAME: RHD2D
    ROOT: data/RHD/evaluation/cropped_bigger   
    DATA_JSON_PATH: data/RHD/evaluation/cropped_anno_bigger.pickle
    IS_TRAIN: False
    TRANSFORMS:
      RESIZE: 256
      FLIP: False
      COLOR_NORISE: False
    THR: 10
    IS_TRAIN: False
    BATCH_SIZE: 2


DATA_DIR: ''
END_EPOCH: 100
CRITERION: CPMMSELoss
GPUS:
- 0
- 1
LOG_DIR: ''
MODEL:
  NAME: openpose_hand
  PRETRAINED_WEIGHT_PATH: 'pretrained_weight/openpose_hand.torch'
  num_joints: 22
OPTIMIZER:
  NAME: RMSprop
  PARAMETERS:
    lr: 2.5e-05
    momentum: 0
    weight_decay: 0
OPTIMIZER_SCHEDULE:
  NAME: StepLR
  PARAMETERS:
    gamma: 0.1
    step_size: 30
METRIC_ITEMS:
  - loss
  - dis
  - PcKAcc
LOG:
  PATH: output
  MONITOR_ITEM:
    - lr
OUTPUT_DIR: output/
START_EPOCH: 0
WORKERS: 40
RESUME_TRAIN: 0
MAIN_METRIC: loss