TRAIN:
  DEBUG: False
  METRIC_ITEMS: # the metric that you wanna track during training
    - loss
    - dis
    - PcKAcc

  DATASET:
    NAME: Combine2D
    CONTAINS:
      RHD2D:
        ROOT: data/RHD/cropped/training/color/ 
        DATA_JSON_PATH: data/RHD/cropped/training/cropped_anno.pickle

    TRANSFORMS:
      RESIZE: 256
      FLIP: True
      COLOR_NORISE: True
    HEATMAP:
      TYPE: Gaussian # Gaussian or Cauchy
      SIGMA: 8 #Ground truth heatmap
    SOFTMAX: False
    NUM_JOINTS: 22
    THR: 20
    IS_TRAIN: True
    BATCH_SIZE: 12
    SHUFFLE: True

VALID:
  DEBUG: False
  IS_VALID: True
  DATASET:
    NAME: Combine2D
    CONTAINS:
      RHD2D:
        ROOT: data/RHD/cropped/evaluation/color/
        DATA_JSON_PATH: data/RHD/cropped/evaluation/cropped_anno.pickle

    TRANSFORMS:
      RESIZE: 256
      FLIP: False
      COLOR_NORISE: False
    HEATMAP:
      TYPE: Gaussian # Gaussian or Cauchy
      SIGMA: 8 #Ground truth heatmap
    SOFTMAX: False
    NUM_JOINTS: 22
    THR: 20
    IS_TRAIN: True
    BATCH_SIZE: 2
    SHUFFLE: False

  METRIC_ITEMS: # the metric that you wanna track during training
    - loss
    - dis
    - PcKAcc

CRITERION: CPMMSELoss
GPUS:
- 0
- 1
LOG_DIR: ''
MODEL:
  NAME: openpose_hand
  PRETRAINED_WEIGHT_PATH: 'pretrained_weight/openpose_hand.torch'
  num_joints: 22
OPTIMIZER:
  NAME: RMSprop
  PARAMETERS:
    lr: 2.5e-05
    momentum: 0
    weight_decay: 0
OPTIMIZER_SCHEDULE:
  NAME: StepLR
  PARAMETERS:
    gamma: 0.1
    step_size: 30
LOG:
  PATH: output
  MONITOR_ITEM:
    - lr
METRIC_ITEMS: # the metric that you wanna track during training
  - loss
  - dis
  - PcKAcc
CURRENT_EPOCH: 0
OUTPUT_DIR: output/
START_EPOCH: 0
WORKERS: 12
RESUME_TRAIN: 0
MAIN_METRIC: PcKAcc
DATA_DIR: ''
END_EPOCH: 100
