CURRENT_EPOCH: 0
IS_VALID: True #validate or just inference
DATASET:
  NAME: SHP2D
  ROOT: data/SHP/2dcrop
  IS_TRAIN: False
  BATCH_SIZE: 30
  SHUFFLE: 0
  DATA_JSON_PATH: data/SHP/2dcrop/label.pickle
  NUM_JOINTS: 21
  THR: 20
  TRANSFORMS:
    RESIZE: 256
  PICK:
    - B1Random
    - B1Counting
  HEATMAP:
    TYPE: Gaussian # Gaussian or Cauchy
    SIGMA: 8 #Ground truth heatmap 

METRIC_ITEMS: # the metric that you wanna track during training
  - loss
  - dis
  - PcKAcc
GPUS:
  - 0
  - 1
LOG_DIR: ''
MODEL:
  NAME: openpose_hand
  PRETRAINED_WEIGHT_PATH: output/Nov 13 17:01:52_train_openpose_hand_RHD_Tencent2D/best/checkpoint.pth.tar
  # PRETRAINED_WEIGHT_PATH: output/Nov 13 16:57:18_train_openpose_hand_RHD2D/best/checkpoint.pth.tar
  # PRETRAINED_WEIGHT_PATH: output/Nov 13 17:01:05_train_openpose_hand_SHP_Tencent2D/best/checkpoint.pth.tar
  # PRETRAINED_WEIGHT_PATH: output/Nov 13 16:57:58_train_openpose_hand_SHP2D/best/checkpoint.pth.tar
  # PRETRAINED_WEIGHT_PATH: output/Nov 12 17:49:44_train_openpose_hand_G_SHP2D/best/checkpoint.pth.tar
  # PRETRAINED_WEIGHT_PATH: 'pretrained_weight/openpose_hand.torch'
  num_joints: 22
CRITERION: CPMMSELoss #CPMMSELoss or DistanceLoss
OUTPUT_DIR: infer_result/
START_EPOCH: 0
WORKERS: 4
DARW_RESULT: False
DEBUG: False
POST_INFER: True