TRAIN:
  THR: 20
  DEBUG: False
  METRIC_ITEMS: # the metric that you wanna track during training
    - loss
    - dis
    - PcKAcc
  DATASET:
    NAME: Tencent2D
    ROOT: data/TencentHand
    DATA_JSON_PATH: data/TencentHand/_train.json
    IS_TRAIN: True
    NUM_JOINTS: 22
    TRANSFORMS:
      RESIZE: 256
      FLIP: True
      COLOR_NORISE: True
    HEATMAP:
      TYPE: Gaussian # Gaussian or Cauchy
      SIGMA: 8 #Ground truth heatmap 
    THR: 20
    IS_TRAIN: True
    BATCH_SIZE: 6
    SHUFFLE: True

VALID:
  THR: 20
  DEBUG: False
  IS_VALID: True
  NUM_JOINTS: 21
  DATASET:
    NAME: Tencent2D
    ROOT: data/TencentHand
    DATA_JSON_PATH: data/TencentHand/_valid.json
    TRANSFORMS:
      RESIZE: 256
      FLIP: False
      COLOR_NORISE: False
    HEATMAP:
      TYPE: Gaussian # Gaussian or Cauchy
      SIGMA: 1 #Ground truth heatmap 
    THR: 20
    NUM_JOINTS: 22
    IS_TRAIN: False
    BATCH_SIZE: 10
  METRIC_ITEMS: # the metric that you wanna track during training
    - loss
    - dis
    - PcKAcc
CRITERION: CPMMSELoss
GPUS:
- 0
- 1
LOG_DIR: ''
MODEL:
  NAME: openpose_hand
  PRETRAINED_WEIGHT_PATH: 'pretrained_weight/openpose_hand.torch'
  num_joints: 22
OPTIMIZER:
  NAME: RMSprop
  PARAMETERS:
    lr: 2.5e-05
    momentum: 0
    weight_decay: 0
OPTIMIZER_SCHEDULE:
  NAME: StepLR
  PARAMETERS:
    gamma: 0.1
    step_size: 30
LOG:
  PATH: output
  MONITOR_ITEM:
    - lr
METRIC_ITEMS: # the metric that you wanna track during training
  - loss
  - dis
  - PcKAcc
CURRENT_EPOCH: 0
OUTPUT_DIR: output/
START_EPOCH: 0
WORKERS: 4
RESUME_TRAIN: 0
MAIN_METRIC: loss
DATA_DIR: ''
END_EPOCH: 100
