CURRENT_EPOCH: 0
TRAIN:
  DEBUG: False
  DATASET:
    NAME: JointsDataset
    CONTAINS:
      RHD3D:
        ROOT: data/RHD/cropped/training/    
        DATA_JSON_PATH: data/RHD/cropped/training/cropped_anno.pickle
    TRANSFORMS:
      RESIZE: 256
      FLIP: False
      COLOR_NORISE: True
    HEATMAP:
      TYPE: Gaussian # Gaussian or Cauchy
      SIGMA: 8 #Ground truth heatmap
    IS_TRAIN: True
    BATCH_SIZE: 20
    SHUFFLE: True
    NUM_JOINTS: 22

VALID:
  DEBUG: False
  IS_VALID: True
  DATASET:
    NAME: JointsDataset
    CONTAINS:
      RHD3D:
        ROOT: data/RHD/cropped/evaluation/   
        DATA_JSON_PATH: data/RHD/cropped/evaluation/cropped_anno.pickle
    TRANSFORMS:
      RESIZE: 256
      FLIP: False
      COLOR_NORISE: False
    HEATMAP:
      TYPE: Gaussian # Gaussian or Cauchy
      SIGMA: 8 #Ground truth heatmap
    IS_TRAIN: False
    BATCH_SIZE: 20
    NUM_JOINTS: 22
DATA_DIR: ''
END_EPOCH: 100

LOG_DIR: ''
MODEL:
  NAME: OpenPose
  NETWORK: 
    NAME: openpose_hand
    PRETRAINED_WEIGHT_PATH: 'pretrained_weight/openpose_hand.torch'
    num_joints: 22
  OPTIMIZER:
    NAME: RMSprop
    PARAMETERS:
      lr: 2.5e-05
      momentum: 0
      weight_decay: 0
  OPTIMIZER_SCHEDULE:
    NAME: StepLR
    PARAMETERS:
      gamma: 0.1
      step_size: 30
  GPUS:
    - 0
    - 1
    - 2
    - 3
LOG:
  PATH: output
  MONITOR_ITEM:
    - lr
METRIC_ITEMS: # the metric that you wanna track during training
  - loss
  - dis2d
MAIN_METRIC: dis3d
OUTPUT_DIR: output/
START_EPOCH: 0
WORKERS: 6
RESUME_TRAIN: 0