CURRENT_EPOCH: 0
TRAIN:
  DEBUG: False
  DATASET:
    NAME: JointsDataset
    IS_TRAIN: True
    BATCH_SIZE: 6
    SHUFFLE: True
    CONTAINS:
      MultiView:
        ROOT: data/multiview/2dCrop
        # PICK:
        #   - 3
        PICK: [3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21]
    REPROCESS:
      TRANSFORMS:
        RESIZE: 256
        FLIP: False
        COLOR_NORISE: True
      HEATMAP:
        TYPE: Gaussian # Gaussian or Cauchy
        SIGMA: 8 #Ground truth heatmap
      NUM_JOINTS: 22
    
    

VALID:
  DEBUG: False
  IS_VALID: True
  NUM_JOINTS: 21
  DATASET:
    NAME: JointsDataset
    IS_TRAIN: False
    BATCH_SIZE: 6
    CONTAINS:
      MultiView:
        ROOT: data/multiview/2dCrop
        PICK: [1, 2]
    REPROCESS:
      TRANSFORMS:
        RESIZE: 256
        FLIP: False
        COLOR_NORISE: False
      HEATMAP:
        TYPE: Gaussian # Gaussian or Cauchy
        SIGMA: 8 #Ground truth heatmap
      NUM_JOINTS: 22

    
DATA_DIR: ''
END_EPOCH: 10

LOG_DIR: ''
MODEL:
  NAME: Weakly_direct_regression
  NETWORKS:
    Regression:
      TYPE: CPMWeaklyDirectRegression
      PRETRAINED_WEIGHT_PATH: 'pretrained_weight/cpmRHD.torch'
      # PRETRAINED_WEIGHT_PATH: 'output/Mar  7 21:58:35_train_Weakly_direct_regression_Combine2D(RHD2D)_valid_Combine2D(RHD2D)/best/model/net_Regression.torch'
      # PRETRAINED_WEIGHT_PATH: output/Mar_13_17:37:40_Weakly_direct_regression_with_depth_train:RHD2D_valid:RHD2D/best/model/net_Regression.torch
      # PRETRAINED_WEIGHT_PATH: output/Apr_17_23:02:20_Weakly_direct_regression_train:MultiView_valid:MultiView/best/model/net_Regression.torch
      num_joints: 22

  OPTIMIZERS:
    Regression:
      NETWORKS:
        - Regression
      TYPE: RMSprop
      PARAMETERS:
        lr: 2.5e-5
        momentum: 0
        weight_decay: 0
      SCHEDULER:
        TYPE: StepLR
        PARAMETERS:
          gamma: 0.1
          step_size: 30
  GPUS:
    - 0
    - 1
    - 2
    - 3
  STAGE: 3
LOG:
  PATH: output
  MONITOR_ITEM:

METRIC_ITEMS: # the metric that you wanna track during training
  - loss
  - dis2d
  - dis3d
  - AUC_20_50
MAIN_METRIC: dis3d

OUTPUT_DIR: output/
START_EPOCH: 0
WORKERS: 6
RESUME_TRAIN: 0
