CURRENT_EPOCH: 0
DATASET:
  NAME: OriginImage
  BATCH_SIZE: 1
  NUM_JOINTS: 21
  SHUFFLE: False
  DATA_FORM: 'img_root' #img_root, block_file
  DATA_PATH: data/origin_image #image_root, h5, pickle
END_EPOCH: 100
GPUS:
- 0
LOG_DIR: ''
MODEL:
  NAME: ICCV17
  PRETRAINED_WEIGHT_PATH: 'pretrained_weight/iccv17_pretrained.torch'
  num_joints: 21
OUTPUT_DIR: infer_result/
START_EPOCH: 0
WORKERS: 1
DARW_RESULT: True