TRAIN:
  DEBUG: True
  METRIC_ITEMS: # the metric that you wanna track during training
  - loss
  - dis
  DATASET:
    NAME: RHD_Tencent
    TENCENT:
      ROOT: data/TencentHand
      DATA_JSON_PATH: data/TencentHand/train.json
      IS_TRAIN: True
      TRANSFORMS:
        RESIZE: 256
        FLIP: True
        COLOR_NORISE: True
    RHD:
      ROOT: data/RHD/training/cropped    
      DATA_JSON_PATH: data/RHD/training/cropped_anno.pickle
      IS_TRAIN: True
      TRANSFORMS:
        RESIZE: 256
        FLIP: True
        COLOR_NORISE: True

    IS_TRAIN: True
    BATCH_SIZE: 24
    SHUFFLE: True
    NUM_JOINTS: 21

VALID:
  DEBUG: False
  IS_VALID: True
  NUM_JOINTS: 21
  METRIC_ITEMS:
    - loss
    - dis
  DATASET:
    NAME: RHD
    ROOT: data/RHD/evaluation/cropped    
    DATA_JSON_PATH: data/RHD/evaluation/cropped_anno.pickle
    IS_TRAIN: False
    TRANSFORMS:
      RESIZE: 256
      FLIP: False
      COLOR_NORISE: False

    IS_TRAIN: False
    BATCH_SIZE: 2
    TRANSFORMS:
      RESIZE: 256
      FLIP: True
      COLOR_NORISE: True

CRITERION: DistanceLoss
GPUS:
- 0
- 1
- 2
- 3
LOG_DIR: ''
MODEL:
  NAME: ICCV17
  PRETRAINED_WEIGHT_PATH: 'pretrained_weight/iccv17_pretrained.torch'
  num_joints: 21
OPTIMIZER:
  NAME: RMSprop
  PARAMETERS:
    lr: 2.5e-05
    momentum: 0
    weight_decay: 0
OPTIMIZER_SCHEDULE:
  NAME: StepLR
  PARAMETERS:
    gamma: 0.1
    step_size: 30
LOG:
  PATH: output
  MONITOR_ITEM:
    - lr
    - train_loss
    - valid_loss
    - train_dis
    - valid_dis
CURRENT_EPOCH: 0
OUTPUT_DIR: output/
START_EPOCH: 0
WORKERS: 48
RESUME_TRAIN: 0
MAIN_METRIC: loss
DATA_DIR: ''
END_EPOCH: 100
