CURRENT_EPOCH: 0
IS_VALID: True #validate or just inference
DATASET:
  NAME: RHD
  ROOT: data/RHD/evaluation/cropped
  IS_TRAIN: True
  BATCH_SIZE: 6

  SHUFFLE: 0
  DATA_JSON_PATH: data/RHD/evaluation/cropped_anno.pickle
  NUM_JOINTS: 21
  TRANSFORMS: False
  HEATMAP:
    TYPE: Gaussian # Gaussian or Cauchy
    SIGMA: 1 #Ground truth heatmap 
METRIC_ITEMS: # the metric that you wanna track during training
  - loss
  - dis
GPUS:
  - 0
  - 1
  - 2
  - 3
LOG_DIR: ''
CRITERION: DistanceLoss
MODEL:
  NAME: ICCV17
  PRETRAINED_WEIGHT_PATH: 'pretrained_weight/iccv17_pretrained.torch'
  num_joints: 21
OUTPUT_DIR: infer_result/
START_EPOCH: 0
WORKERS: 1
DARW_RESULT: False
DEBUG: False