CURRENT_EPOCH: 0
VALID:
  IS_INFERNCE: False #set ture if only wanna get output of the model
  DEBUG: False
  DATASET:
    NAME: RHD
    ROOT: data/RHD/evaluation/cropped
    IS_TRAIN: False
    BATCH_SIZE: 2
    DATA_JSON_PATH: data/RHD/evaluation/cropped_anno.pickle
    TRANSFORMS: True
    NUM_JOINTS: 21
    METRICITEMS:
      - loss
      - acc
      - dis
DATA_DIR: ''
END_EPOCH: 100
GPUS:
- 4
- 5
- 6
- 7
LOG_DIR: ''
MODEL:
  NAME: ICCV17
  PRETRAINED: 'pretrained/iccv17_pose_net_pretrained.pickle'
  num_joints: 21
OPTIMIZER:
  NAME: RMSprop
  PARAMETERS:
    lr: 2.5e-05
    momentum: 0
    weight_decay: 0
OPTIMIZER_SCHEDULE:
  NAME: StepLR
  PARAMETERS:
    gamma: 0.1
    step_size: 30
LOG:
  PATH: output
  MONITOR_ITEM:
    - lr
    - train_loss
    - valid_loss
    - train_acc
    - valid_acc
OUTPUT_DIR: output/
START_EPOCH: 0
WORKERS: 8
RESUME_TRAIN: 0
