CURRENT_EPOCH: 0
IS_VALID: False #validate or just inference
DATASET:
  NAME: SHP
  ROOT: data/SHP/
  IS_TRAIN: False
  BATCH_SIZE: 10
  SHUFFLE: 0
  DATA_JSON_PATH: data/SHP/labels
  NUM_JOINTS: 22
  TRANSFORMS: False
  METRICITEMS: # the metric that you wanna track during training
    - loss
    - acc
    - dis
GPUS:
  - 0
  - 1
  - 2
LOG_DIR: ''
MODEL:
  NAME: openpose_hand
  PRETRAINED_WEIGHT_PATH: 'pretrained_weight/openpose_hand_model.torch'
  num_joints: 22

METRIC_ITEMS: # the metric that you wanna track during training
  - loss
  - acc
CRITERION: CPMMSELoss
OUTPUT_DIR: infer_result/
START_EPOCH: 0
WORKERS: 40
DARW_RESULT: True
DEBUG: True