CURRENT_EPOCH: 0
TRAIN:
  DEBUG: False
  DATASET:
    NAME: SHP
    ROOT: data/SHP
    IS_TRAIN: True
    BATCH_SIZE: 2
    SHUFFLE: 0
    DATA_JSON_PATH: data/SHP/labels
    TRANSFORMS: True
    NUM_JOINTS: 21
VALID:
  DEBUG: False
  DATASET:
    NAME: SHP
    ROOT: data/SHP/
    IS_TRAIN: False
    BATCH_SIZE: 2
    DATA_JSON_PATH: data/SHP/labels
    TRANSFORMS: True
    NUM_JOINTS: 21
DATA_DIR: ''
END_EPOCH: 100
GPUS:
- 0
- 1
LOG_DIR: ''
MODEL:
  NAME: ICCV17
  PRETRAINED: 'pretrained_weight/iccv17_pose_net_pretrained.torch'
  num_joints: 21
OPTIMIZER:
  NAME: RMSprop
  PARAMETERS:
    lr: 2.5e-05
    momentum: 0
    weight_decay: 0
OPTIMIZER_SCHEDULE:
  NAME: StepLR
  PARAMETERS:
    gamma: 0.1
    step_size: 30
LOG:
  PATH: output
  MONITOR_ITEM:
    - lr
    - train_loss
    - valid_loss
    - train_acc
    - valid_acc
OUTPUT_DIR: output/
START_EPOCH: 0
WORKERS: 8
RESUME_TRAIN: 0
