CURRENT_EPOCH: 0
IS_VALID: True
TRAIN:
  DEBUG: False
  METRIC_ITEMS: # the metric that you wanna track during training
    - loss
    - dis
  DATASET:
    NAME: SHP
    ROOT: data/SHP
    DATA_JSON_PATH: data/SHP/labels
    PICK:
      - B2Counting
      - B3Counting
      - B4Counting
      - B5Counting
      - B6Counting
      - B2Random
      - B3Random
      - B4Random
      - B5Random
      - B6Random
    IS_TRAIN: True
    TRANSFORMS:
      RESIZE: 256
      FLIP: True
      COLOR_NORISE: True
    IS_TRAIN: True
    BATCH_SIZE: 6
    SHUFFLE: True
    NUM_JOINTS: 21
VALID:
  METRIC_ITEMS: # the metric that you wanna track during training
    - loss
    - dis
  DEBUG: False
  DATASET:
    PICK:
      - B1Counting
      - B1Random
    NAME: SHP
    ROOT: data/SHP/
    DATA_JSON_PATH: data/SHP/labels
    TRANSFORMS:
      RESIZE: 256
      FLIP: False
      COLOR_NORISE: False

    IS_TRAIN: False
    BATCH_SIZE: 6
METRIC_ITEMS: # the metric that you wanna track during training
  - loss
  - dis
DATA_DIR: ''
END_EPOCH: 100
GPUS:
- 0
- 1
LOG_DIR: ''
MODEL:
  NAME: ICCV17
  PRETRAINED_WEIGHT_PATH: 'pretrained_weight/iccv17-rhd-stb.torch'
  num_joints: 21
OPTIMIZER:
  NAME: RMSprop
  PARAMETERS:
    lr: 2.5e-05
    momentum: 0
    weight_decay: 0
OPTIMIZER_SCHEDULE:
  NAME: StepLR
  PARAMETERS:
    gamma: 0.1
    step_size: 30
LOG:
  PATH: output
  MONITOR_ITEM:
    - lr
OUTPUT_DIR: output/
START_EPOCH: 0
WORKERS: 8
RESUME_TRAIN: 0
CRITERION: DistanceLoss
MAIN_METRIC: loss